INSERT INTO CATEGORIAS VALUES	
	(NULL,'ARMAS',NOW(),NOW(),NULL),
	(NULL,'CONSTRUCCIÓN',NOW(),NOW(),NULL),
	(NULL,'ROPA',NOW(),NOW(),NULL);

INSERT INTO PRODUCTOS VALUES
	(NULL, 1, 'Pistola TAURUS TH9 (Full Size) (10017588)', 'Pistola TAURUS 9x19mm (9mm PB) pavonada-sintética de 17 tiroS', 'TAURUS', NULL, NULL,2456.30, 20, NULL, 5, NOW(),NOW(), NULL);