CREATE DATABASE IF NOT EXISTS ENTREGABLE01;
USE ENTREGABLE01;

CREATE TABLE IF NOT EXISTS CATEGORIAS(
	ID 			INT 		AUTO_INCREMENT PRIMARY KEY,
    NOMBRE 		VARCHAR(50) NOT NULL UNIQUE,
    created_at 	DATETIME,
    updated_at 	DATETIME,
    deleted_at 	DATETIME
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS PRODUCTOS(
	ID				INT AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORIA 	INT NOT NULL,
    NOMBRE 			VARCHAR(70) NOT NULL,
    DESCRIPCION 	TEXT NOT NULL,
    MARCA 			VARCHAR(70),
    MODELO 			VARCHAR(70),
    IMAGEN 			TEXT,
    PRECIO 			DECIMAL(7,2) NOT NULL,
    DESCUENTO		INT,
    PRECIO_ENVIO 	DECIMAL(5,2),
    CUOTAS 			INT,
    created_at 		DATETIME,
    updated_at 		DATETIME,
    deleted_at 		DATETIME,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID)
)ENGINE=INNODB;
